<div class="z-brands">
	<div class="z-container">
		<ul>
			<li class="z-col-twelve">
				<img src="./img/brands/brands-gaf.gif" class="z-brand-logo z-gaf" alt="Gaf" />
				<img src="./img/brands/brands-ct.png" class="z-brand-logo z-ct" alt="CertainTeed" />
				<img src="./img/brands/brands-oc.gif" class="z-brand-logo z-oc" alt="Owens Corning" />
			</li>
			<li class="z-col-twelve">
				<a href="https://www.bbb.org/us/al/hazel-green/profile/roofing-contractors/southern-pride-roofing-construction-llc-0513-900042053" title="BBB Accredited" target="_blank"><img src="./img/brands/brands-bbb.gif" class="z-brand-logo z-bbb" alt="BBB Accredited" /></a>
				<a href="https://www.tamko.com/find-a-pro" title="Tamco Certified Contractor, Search Zip Code: 35750" target="_blank"><img src="./img/brands/brands-tam.gif" class="z-brand-logo z-tam" alt="Tamco Certified Contractor" /></a>
			</li>
		</ul>
	</div><!-- #container -->
</div><!-- #brands -->