<div class="z-footer clearfix">
    <div class="z-container">
        <div class="z-footer-columns z-col-three">
            
                <h4>Navigate</h4>
                <li><a href="index.aspx">Home</a></li>
                <li><a href="about.aspx">About</a></li>
                <li><a href="estimate.aspx">Estimate</a></li>
<!--                <li><a href="testimonials.aspx">Testimonials</a></li> -->
                <li><a href="contact.aspx">Contact</a></li>
                <li><a href="abitasprings.aspx">Location</a></li>
                <li><a href="privacy-policy.aspx">Privacy Policy</a></li>
            
        </div>                

        <div class="z-footer-columns z-col-three">
            
                <h4>Services</h4>
                <li><a href="residential-services.aspx">Residential Services</a></li>
                <li><a href="commercial-services.aspx">Commercial Services</a></li>
                <li><a href="storm-damage.aspx">Storm Damage</a></li>
                <li><a href="avoid-a-roofing-scam.aspx">Avoid a Roofing Scam</a></li>
           
        </div>          

        <div class="z-footer-columns z-col-three">
            
                <h4>Contact Information</h4>
                <span itemprop="company"><li>Pelican Roofing Group</li></span>
                <span itemprop="tel"><li>855-Pelican</li></span>
                <span itemprop="tel"><li>855-735-4226</li></span>
                <span itemprop="address"><li>22215 Prats Dairy Rd., Abita Springs, LA 70420</li></span>
				
<!--                <li><a href="licensed-insurance.aspx">license & Insurance</a></li> -->
            
        </div>                

		
        <div class="z-footer-columns z-col-three z-last" itemscope itemtype="http://schema.org/Person">
            <li>
                <a href="http://www.homeadvisor.com/rated.PelicanRoofingGroup.91643908.html"><img alt="HomeAdvisor Screened & Approved Business" style="display:block;" src="http://www.homeadvisor.com/images/sp-badges/soap-solid-border.png?sp=91643908&key=4dc1fd280baa4110da41fcdd073b93cf" /></a>
			</li>	
            
        </div>
    </div><!-- #container -->
</div><!-- #footer -->

<div class="z-copyright clearfix">
    <div class="z-container">
        <div class="z-col-eight">
            <p>License #: 83416565 - Copyright © Pelican Roofing Company LLC. All rights reserved.</p>
        </div>    
        <div class="z-col-four">
            <ul class="z-social-break">
                <li><a href="https://www.facebook.com/PELICANROOFINGLOUISIANA" target="_blank"><i class="z-icon icon-facebook"></i></a></li>
                <li><a href="https://www.instagram.com/pelicanroofinggroup/" target="_blank"><i class="z-icon icon-instagram"></i></a></li>
                <li><a href="https://twitter.com/pelican_roofing" target="_blank"><i class="z-icon icon-twitter"></i></a></li>
            </ul>
        </div>
    </div><!-- #container -->
</div><!-- #copyright -->