<script type="text/javascript" src="js/facebookpixelcode.js"></script>
<noscript><img height="1" width="1" src="https://www.facebook.com/tr?id=693279484505219&ev=PageView&noscript=1" /></noscript>

<header class="clearfix">
    <div class="z-show">
        <div class="z-top-bar">
            <div class="z-container-full">
                <p>We handle all insurance claims. #1 in Louisiana, Pelican Roofing uses hail resistant asphalt shingles. Our roofs are built to last.</p>
                <span class="z-call-no">Call Us Now: 855-735-4226</span>
            </div>
        </div><!-- #top-bar -->

        <div class="z-header z-container-full clearfix">
            <h1 class="z-site-branding z-col"><a href="index.aspx"><img src="./img/logo.png" alt="Logo" /></a></h1><!-- #logo -->

            <div class="z-site-branding-dex z-col-two z-col">
                <h1><a href="index.aspx"><img src="./img/logo.jpg" alt="Logo"  /></a></h1>
            </div><!-- #main-site-branding -->

            <div class="z-main-nav z-right-mb z-col z-right-dx">
                <div class="z-mobile-nav-trigger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div><!-- #main-nav-mobile -->
        </div><!-- show on mobile -->
    </div><!-- show on mobile -->

    <div id="stick" class="z-show-dx">
        <div class="z-top-bar">
            <div class="z-container-full">
                <p>We handle all insurance claims. #1 in Louisiana, Pelican Roofing uses hail resistant asphalt shingles. Our roofs are built to last.</p>
                <span class="z-call-no">Call Us Now: 855-735-4226</span>
            </div>
        </div><!-- #top-bar -->

        <div class="z-header z-container-full clearfix">
            <div class="z-site-branding-dex z-col-two z-col">
                <h1><a href="index.aspx"><img src="./img/logo.jpg" alt="Logo" /></a></h1>
            </div><!-- #main-site-branding -->

            <div class="z-header-container z-col-ten z-alpha-right">
                <div class="z-malarkey-logo z-col z-alpha-left">
                    <a href="https://malarkeyroofing.com/products" title="Malarkey Roofing Products Defining Excellence" target="_blank"><img src="./img/MalarkeyRoofingProducts.png" alt="Malarkey Roofing Products" /></a>
                </div><!-- #main-malarkey-branding -->

				<div class="z-call-numbers z-col">
                <p>
				<span>855-Pelican</span>
                <span>855-735-4226</span>
                </p>
                </div><!-- #call-numbers -->

                <div class="z-resources z-show-dx z-col z-right-dx">
                    <a class="z-button z-button-red z-button-highlight " href="estimate.aspx">Request A Quote</a>
                </div><!-- #resources -->

                <div class="z-bbb-logo z-col z-right-dx">
                    <a href=# title="BBB Accredited" target="_blank"><img src="./img/brands-bbb.png" alt="BBB Accredited" /></a>
                </div><!-- #main-bbb-branding -->

                <div class="clearfix"></div><!-- #clearfix -->

                <nav class="z-main-nav-dex">
                    <ul>
                        <li class="z-index-link"><a href="index.aspx">Home</a></li>
                        <li class="z-about-link"><a href="about.aspx">About</a></li>
                        <li class="z-services-link no-click"><a href="#">Service</a>
                            <ul>
                                <li class="z-storm-damage-link"><a href="storm-damage.aspx">Storm Damage</a></li>
                                <li class="z-residential-services-link"><a href="residential-services.aspx">Residential Services</a></li>
                                <li class="z-commercial-services-link"><a href="commercial-services.aspx">Commercial Services</a></li>
                                <li class="z-avoid-a-scam-link"><a href="avoid-a-roofing-scam.aspx">Avoid a Roofing Scam</a></li>
                                <li class="z-abitasprings-link"><a href="abitasprings.aspx">Location</a></li>
                            </ul>
                        </li>
                        <li class="z-estimate-link"><a href="estimate.aspx">Estimate</a>
                            <ul>
                                <li class="z-warranty-link"><a href="warranty-questions.aspx">Warranty Questions</a></li>
                            </ul>
                        </li>
    <!--                    <li class="z-testimonial-link"><a href="testimonials.aspx">Testimonials</a></li> -->
                        <li class="z-contact-link"><a href="contact.aspx">Contact</a></li>
                        <li class="z-financing-link"><a href="financing.aspx">Financing</a></li>
    <!--                    <li class="z-licensed-insurance-link"><a href="licensed-insurance.aspx">license & Insurance</a></li> -->
                    </ul>
                </nav><!-- #main-nav-dextop -->
            </div><!-- #header-container -->

        </div><!-- #show-on-dextop -->
    </div><!-- #stick-->
</header><!-- #header -->