<div class="z-inline-cta clearfix">
    <div class="z-container">
    	<div class="z-col-twelve">
			<h3 class="z-section-title">Insurance company not paying enough money for the damages to your home? Pelican Roofing and its team are well seasoned in supplementing insurance companies and getting approval for shortfalls. Give us a call for more details.&nbsp;<a href="tel:855-735-4226">855-735-4226</a></h3>
    	</div><!-- #column -->
    </div><!-- #container -->
</div><!-- #testimonial -->