<div class="z-services clearfix">
    <div class="z-container">
    	<div class="z-col-twelve">
    		<h1 class="z-section-title">Roofing & <span>Malarkey</span></h1>
    		<h4 class="z-sub-title">As a licensed roofing company, we at Pelican focus exclusively on giving the best quality roof and service for Louisiana weather.</h4>
        </div><!-- #column -->
    		
        <div class="z-service-box z-col-six">
			<ul>
				<h4>Pelican Roofing</h4>
				<li>A Name You Can Trust</li>
				<li>Unmatched Service</li>
				<li>BBB A+ Rating</li>
				<li>Fully Insured</li>
				<li><a class="z-button z-button-grey" href="residential-services.aspx">Read More</a></li>
			</ul>
		</div><!-- #service-box -->    		

		<div class="z-service-box z-col-six z-last">
			<ul>
				<h4>Malarkey</h4>
				<li>Hurricane Resistant Shingle</li> 
				<li>Hail Resistant</li> 
				<li>NEX Technology</li>
				<li>Green and Great for our Environment</li>
				<li><a class="z-button z-button-grey" href="commercial-services.aspx">Read More</a></li>
			</ul>
		</div><!-- #service-box -->
    </div><!-- #container -->
</div><!-- #testimonial -->