<div class="z-sidebar-reference">
    <div class="z-box z-box-grey">
        <h3>Client References</h3>

        <b>Jack & Diane Owens</b>
        <p>123 Main Street, .....</p>

        <div class="z-spacer-20"></div><!-- #spacer -->            

        <b>John Smith</b>
        <p>123 Main Street, .....</p>

        <div class="z-spacer-20"></div><!-- #spacer -->            

        <b>John Smith</b>
        <p>123 Main Street, .....</p>

        <div class="z-spacer-20"></div><!-- #spacer -->            

        <b>John Smith</b>
        <p>123 Main Street, .....</p>

        <div class="z-spacer-20"></div><!-- #spacer -->            

        <b>John Smith</b>
        <p>123 Main Street, .....</p>

        <div class="z-spacer-20"></div><!-- #spacer -->            

        <b>John Smith</b>
        <p>123 Main Street, .....</p>

        <div class="z-spacer-20"></div><!-- #spacer -->            

        <b>John Smith</b>
        <p>123 Main Street, .....</p>

        <div class="z-spacer-20"></div><!-- #spacer -->       

        <b>John Smith</b>
        <p>123 Main Street, .....</p>

    </div><!-- #box -->
</div><!-- #sidebar-address -->
































