<div class="z-box z-box-blue">
    <h4>Here is how Pelican Roofing does business:</h4>

    <p><b>-</b> A thorough inspection of the roof will be done so that all damages and needs are identified.</p>

    <p><b>-</b> Should this be storm-related, we will work with the insurance adjustor to make sure that they are aware of, and pays for the damages found. We will make sure that the adjustor agrees with our first inspection findings and agrees to pay for those damages found.</p>

    <p><b>-</b> Once everything is agreed upon, Pelican Roofing goes to work on the repairs for your home.</p>

    <p><b>-</b> Once all is complete, Pelican Roofing will bill your insurance company or you for the final payment.</p>
</div><!-- #sidebox -->