<div class="z-sidebar-services">
    <div class="z-box z-box-blue">
	    <h3>Roofing</h3>
	    <p>All roofing comes with a warranty from Pelican Roofing. Each application provides its own manufacturer’s warranty.</p>
		<ol>
			<li>Installation</li>
			<li>Shingles</li>
			<li>Corrugated Sheet Metal</li>
			<li>Built-up Roofing</li>
			<li>Tile and Slate</li>
			<li>Repairs / Replacement</li>
			<li>Waterproofing</li>
			<li>Maintenance</li>
			<li>Post Job Completion Maintenance</li>
			<li>Preventative Maintenance</li>
		</ol>
		
		<!-- 
		<div class="z-spacer-25"></div>
		
		<h3>Framing</h3>
		<p>Our residential framing services include fiber cement siding, fire and storm restoration, demolition, new construction, room additions, attic conversions, flat roof conversions, interior remodeling and wall removal, roof and wall framing, major structural repairs such as sagging floors and roofs, general carpentry and much more.</p>

		<div class="z-spacer-25"></div>

		<ol>
			<h3>Exterior</h3>
			<li>We excel at siding repairs and new installations</li>
			<li>Vinyl, hardi-board, masonite, and wood</li>
			<li>Fascia, soffit, and gutters</li>
			<li>Windows</li>
			<li>Replacement and New Construction</li>
			<li>Doors</li>
			<li>Exterior painting, deck cleaning and staining</li>
			<li>Deck construction</li>
			<li>Demolition and Removal of old deck</li>
			<li>Fencing</li>
			<li>Wood, vinyl, metal, and chain link</li>
		</ol>

		<div class="z-spacer-25"></div>

		<ol>
		​	<h3>Flooring</h3>
			<li>Removal and Disposal of old flooring</li>
			<li>Appropriate new floor preparation</li>
			<li>Professional Installation</li>
			<li>True hardwood, engineered hardwood, glued woods, laminates, slate, tile, stone, sheet vinyl, strip vinyl, VCT, and carpeting.</li>
		</ol> -->
    </div><!-- #box -->
</div><!-- #sidebar-services -->
