<div class="z-slideshow-container z-show-dx">
	<div class="z-slideshow-1 z-col-30p">
	    <img src="./img/slideshow/Malarkey-Highlander-Sienna-Blend.jpg" alt="Roof 5"/>
	    <img src="./img/slideshow/Malarkey-Legacy-Black-Oak.jpg" alt="Roof 5"/>
	    <img src="./img/slideshow/kirkwood5.jpg" alt="Roof 5"/>
	</div><!-- #slideshow -->

	<div class="feature-video z-col-40p">
<!--	<div class='video-container'><iframe src='https://player.vimeo.com/video/353818304' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div> 
		<div class='video-container'><iframe src='https://player.vimeo.com/video/384807312' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>-->
<script src="https://fast.wistia.com/embed/medias/l0vkh4jiof.jsonp" async></script><script src="https://fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><div class="wistia_embed wistia_async_l0vkh4jiof videoFoam=true" style="height:100%;position:relative;width:100%"><div class="wistia_swatch" style="height:100%;left:0;opacity:0;overflow:hidden;position:absolute;top:0;transition:opacity 200ms;width:100%;"><img src="https://fast.wistia.com/embed/medias/l0vkh4jiof/swatch" style="filter:blur(5px);height:100%;object-fit:contain;width:100%;" alt="" aria-hidden="true" onload="this.parentNode.style.opacity=1;" /></div></div></div></div>	</div><!-- #feature-video -->

	<div class="z-slideshow-3 z-col-30p">
	    <img src="./img/slideshow/Malarkey-Vista-Midnight-Black.jpg" alt="Roof 5"/>
	    <img src="./img/slideshow/Malarkey-Windsor-XL-Weathered-Wood.jpg" alt="Roof 5"/>
	    <img src="./img/slideshow/WOODCREST4.jpg" alt="Roof 4"/>
	</div><!-- #slideshow -->
</div><!-- #slideshow-container-dextop-->

<div class="feature-video z-show">
	<div class="z-col-twelve">
<!--	<div class='video-container'><iframe src='https://player.vimeo.com/video/353818304' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div> 
		<div class='video-container'><iframe src='https://player.vimeo.com/video/384807312' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>-->
		<script src="https://fast.wistia.com/embed/medias/l0vkh4jiof.jsonp" async></script><script src="https://fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><div class="wistia_embed wistia_async_l0vkh4jiof videoFoam=true" style="height:100%;position:relative;width:100%"><div class="wistia_swatch" style="height:100%;left:0;opacity:0;overflow:hidden;position:absolute;top:0;transition:opacity 200ms;width:100%;"><img src="https://fast.wistia.com/embed/medias/l0vkh4jiof/swatch" style="filter:blur(5px);height:100%;object-fit:contain;width:100%;" alt="" aria-hidden="true" onload="this.parentNode.style.opacity=1;" /></div></div></div></div>
	</div><!-- column-twelve -->
	<div class="z-spacer-25"></div>
</div><!-- #feature-video -->

<div class="z-slideshow-container z-show">
	<div class="z-slideshow-1 z-col-twelve">
	    <img src="./img/slideshow/Malarkey-Highlander-Sienna-Blend.jpg" alt="Roof 5"/>
	    <img src="./img/slideshow/Malarkey-Legacy-Black-Oak.jpg" alt="Roof 5"/>
	    <img src="./img/slideshow/kirkwood5.jpg" alt="Roof 5"/>
	    <img src="./img/slideshow/Malarkey-Vista-Midnight-Black.jpg" alt="Roof 5"/>
	    <img src="./img/slideshow/Malarkey-Windsor-XL-Weathered-Wood.jpg" alt="Roof 5"/>
	    <img src="./img/slideshow/WOODCREST4.jpg" alt="Roof 4"/>
	</div><!-- #slideshow -->
</div><!-- #slideshow-container-dextop-->