<div class="z-storm clearfix">
    <div class="z-container">
        <div class="z-col-eight-lg z-col-twelve">
            <div class="cocoen">
                <img src="img/storm-damage-before-after/before-roof.jpg" alt="Storm Before">
                <img src="img/storm-damage-before-after/after-roof.jpg" alt="Storm After">
            </div>
            <span><p>Grab the Drawer Line and & Slide to See the Difference.</p></span>
        </div>
        <div class="z-col-four-lg z-col-twelve">
    		<h2 class="z-section-title">Storm <span>Damage?</span></h2>
    		<h4 class="z-sub-title">Hail? Wind? Flood? Fire? Water?</h4>  		
    		<p>Pelican Roofing has worked with all major insurance carriers for years and can handle claims fast, so you don't have to!!!</p>

			<p>From dealing with inspectors to mortgage companies, we've got you covered!!</p>

			<p>Water Claims OR Busted Pipes</p>
			<p>Fire Claims</p>
			<p>All Storm, Wind And Hail Claims.</p>
			<a class="z-button z-button-yellow z-button-large" href="storm-damage.aspx">Read More</a>
    	</div><!-- #column -->
    </div><!-- #container -->
</div><!-- #testimonial -->