<div class="z-testimonial clearfix">
    <div class="z-container">
    	<div class="z-col-twelve">
			<h2 class="z-section-title">Real Client <span>Testimonials</span></h2>
			
			<div class="z-spacer-25"></div><!-- #spacer -->

			<p>"I Love Pelican Roofing!!!" They were so nice, and they took the time to explain everything and answer all my questions. They were extremely professional, courteous, and my roof looks amazing!</p><!-- Testimonial-quote -->
			
			<div class="z-seprator"></div><!-- #seprator -->
			
			<div class="z-testimonial-by">Lyle French</div><!-- #testimonial-by -->
			<div class="z-testimonial-by-post">New Orleans, LA</div><!-- #testimonial-by-post -->
    	</div><!-- #column -->
    </div><!-- #container -->
</div><!-- #testimonial -->